USE QACOP

GO

SELECT DISTINCT
(SELECT COUNT (STATUS) from SP_Utility_DQ_OUTPUT WHERE SP_Utility_DQ_OUTPUT.STATUS = 'FAILED') AS SCENARIOS_FAILED,
(SELECT COUNT(STATUS)  from SP_Utility_DQ_OUTPUT WHERE SP_Utility_DQ_OUTPUT.STATUS = 'PASSED') AS SCENARIOS_PASSED,
(SELECT COUNT(STATUS)  from SP_Utility_DQ_OUTPUT) AS TOTAL_SCENARIOS FROM SP_Utility_DQ_OUTPUT 

GO